### ISSUE TITLE
Not compatible with Java 8

### ISSUE THREAD

**Issue by zkz19872009** [leonfancy/oggus#1]
Compile failed 
files-2.1/org.chenliang.oggus/oggus/1.0.0/2223b9ddae6120fa4d4c0076a573d0428033bf68/oggus-1.0.0.jar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)

**Comment by leonfancy** [comment]
Please give more detail about how you use it.

**Comment by zkz19872009** [comment]
Has been introduced into my app implementation 'org.chenliang.oggus:oggus:1.0.0'  and compile failed。

**Comment by leonfancy** [comment]
OK, this is because oggus are compiled target to Java 11, however you are using Java 8. I can publish a Java 8 compatible version.

**Comment by zkz19872009** [comment]
To ask a question, the remote control grab opus does not take the lead file, the player can not play the opus format, do you know how to join the header file

**Comment by leonfancy** [comment]
Fixed in release 1.1.0.

**Comment by zkz19872009** [comment]
sir,
ERROR: Failed to resolve: org.chenliang.oggus:oggus:1.1.0
Show in Project Structure dialog
Affected Modules: app

**Comment by leonfancy** [comment]
Sorry, I forgot to publish it to maven repository. It would be fixed, please try again.

**Comment by zkz19872009** [comment]
sir,
i use this:
        OggOpusStream oggOpusStream = null;
        try {
            oggOpusStream = OggOpusStream.from("audio/test03.opus");
        } catch (IOException e) {
            e.printStackTrace();
        }
        IdHeader idHeader = oggOpusStream.getIdHeader();
crash:
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.chenliang.oggus.opus.IdHeader org.chenliang.oggus.opus.OggOpusStream.getIdHeader()' on a null object reference
        at com.example.testopus.MainActivity.initOpus(MainActivity.java:36)
        at com.example.testopus.MainActivity.onCreate(MainActivity.java:26)

**Comment by leonfancy** [comment]
This is the problem with your own code.
